\
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
BSDS500 evaluation launcher for DMOR-Edge (Windows-friendly).

This version fixes the common "pipeline MATLAB path differs from interactive MATLAB"
issue by:
1) Generating a self-contained MATLAB eval script that calls restoredefaultpath()
   and then explicitly addpath() the repo's BSDSbench + pdollar_toolbox.
2) Setting MATLABPATH env var before launching MATLAB (extra safety).

It does NOT modify BSDSBench sources (edgesEvalDir/edgesEvalImg/fevalDistr).

Usage example:
  python pipelines/run_bsds500_pipeline.py ^
      --repo_root D:\\Users\\JJzhe\\code\\github\\DMOR-Edge ^
      --bsds_root D:\\Users\\JJzhe\\code\\github\\DMOR-Edge\\dataset\\BSDS500\\data ^
      --matlab "D:\\Program Files\\MATLAB\\R2025a\\bin\\matlab.exe" ^
      --pred_dir D:\\Users\\JJzhe\\code\\github\\outputs\\BSDS500\\DMOR\\test_png ^
      --out_dir  D:\\Users\\JJzhe\\code\\github\\outputs\\BSDS500\\DMOR\\eval_official ^
      --eval_type parfor

If your MATLAB does NOT have Parallel Computing Toolbox, use:
  --eval_type local
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path
from textwrap import dedent


def _norm(p: str | Path) -> str:
    """Use forward slashes for MATLAB compatibility."""
    return str(Path(p).resolve()).replace("\\", "/")


def _write_matlab_eval_script(
    script_path: Path,
    repo_root: Path,
    bsds_root: Path,
    pred_dir: Path,
    out_dir: Path,
    eval_type: str = "parfor",  # 'parfor' or 'local'
) -> None:
    repo_root_s = _norm(repo_root)
    bsds_root_s = _norm(bsds_root)
    pred_dir_s = _norm(pred_dir)
    out_dir_s = _norm(out_dir)

    m = dedent(f"""
    % AUTO-GENERATED by pipelines/run_bsds500_pipeline.py
    clear; clc;

    repoRoot  = '{repo_root_s}';
    BSDS_ROOT = '{bsds_root_s}';
    PRED_DIR  = '{pred_dir_s}';
    OUT_DIR   = '{out_dir_s}';

    fprintf('[eval] repoRoot  = %s\\n', repoRoot);
    fprintf('[eval] BSDS_ROOT = %s\\n', BSDS_ROOT);
    fprintf('[eval] PRED_DIR  = %s\\n', PRED_DIR);
    fprintf('[eval] OUT_DIR   = %s\\n', OUT_DIR);

    % ---- HARD RESET PATH to avoid picking up other toolboxes/projects ----
    restoredefaultpath; rehash toolboxcache;

    % ---- Add ONLY the repo's official benchmark/toolbox paths ----
    addpath(genpath(fullfile(repoRoot,'tools','BSDSbench')));
    addpath(genpath(fullfile(repoRoot,'tools','pdollar_toolbox')));
    rehash;

    fprintf('--- PATH CHECK (pipeline MATLAB) ---\\n');
    disp(which('edgesEvalDir','-all'));
    disp(which('edgesEvalImg','-all'));
    disp(which('fevalDistr','-all'));
    fprintf('-----------------------------------\\n');

    assert(exist(BSDS_ROOT,'dir')==7, 'BSDS_ROOT not found');
    GT_DIR = fullfile(BSDS_ROOT,'groundTruth','test');
    assert(exist(GT_DIR,'dir')==7, 'Missing groundTruth/test');

    assert(exist(PRED_DIR,'dir')==7, 'PRED_DIR not found');
    predFiles = dir(fullfile(PRED_DIR,'*.png'));
    assert(~isempty(predFiles), 'No prediction PNGs found in PRED_DIR');
    fprintf('[eval] Found %d prediction PNGs\\n', numel(predFiles));
    fprintf('[eval] Example prediction: %s\\n', predFiles(1).name);

    gtMats = dir(fullfile(GT_DIR,'*.mat'));
    assert(~isempty(gtMats), 'No GT .mat found under groundTruth/test');
    fprintf('[eval] Found %d GT mats in %s\\n', numel(gtMats), GT_DIR);

    if ~exist(OUT_DIR,'dir'), mkdir(OUT_DIR); end

    fprintf('[eval] Running BSDSBench edgesEvalDir...\\n');
    try
        % Official evaluator; fevalDistr affects speed only.
        edgesEvalDir('resDir', PRED_DIR, 'gtDir', GT_DIR, 'pDistr', {{'type','{eval_type}'}} , 'cleanup', 0);
    catch ME
        disp(getReport(ME,'extended'));
        error('edgesEvalDir failed');
    end

    % Move results into OUT_DIR for pipeline consistency
    src = [PRED_DIR '-eval'];
    dst = fullfile(OUT_DIR, 'test_png-eval');
    if exist(dst,'dir'), rmdir(dst,'s'); end
    if exist(src,'dir')
        movefile(src, dst);
        fprintf('[eval] Moved eval results to: %s\\n', dst);
    else
        error('Expected eval directory not found: %s', src);
    end

    fprintf('[eval] Done.\\n');
    """).strip() + "\n"

    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text(m, encoding="utf-8")


def _run_matlab(matlab_exe: Path, script_m: Path, cwd: Path, extra_env: dict[str, str]) -> None:
    matlab_exe = matlab_exe.resolve()
    if not matlab_exe.exists():
        raise FileNotFoundError(f"MATLAB not found: {matlab_exe}")

    cmd = [
        str(matlab_exe),
        "-batch",
        f"run('{_norm(script_m)}');"
    ]

    print(f"[run] matlab   = {matlab_exe}")
    print(f"[run] script  = {_norm(script_m)}")

    proc = subprocess.run(
        cmd,
        cwd=str(cwd),
        env={**os.environ, **extra_env},
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    print(proc.stdout)
    if proc.returncode != 0:
        raise RuntimeError(f"MATLAB exited with code {proc.returncode}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo_root", type=str, default=None, help="Path to DMOR-Edge repo root")
    ap.add_argument("--bsds_root", type=str, default=None, help="Path to BSDS500 'data' directory")
    ap.add_argument("--matlab", type=str, required=True, help="Path to matlab.exe")
    ap.add_argument("--pred_dir", type=str, required=True, help="Directory containing prediction PNGs (test split)")
    ap.add_argument("--out_dir", type=str, required=True, help="Directory to store official eval outputs")
    ap.add_argument("--eval_type", type=str, default="parfor", choices=["parfor", "local"],
                    help="fevalDistr backend: parfor (requires Parallel Computing Toolbox) or local")
    args = ap.parse_args()

    repo_root = Path(args.repo_root).resolve() if args.repo_root else Path(__file__).resolve().parents[1]
    bsds_root = Path(args.bsds_root).resolve() if args.bsds_root else (repo_root / "dataset" / "BSDS500" / "data")
    pred_dir = Path(args.pred_dir).resolve()
    out_dir = Path(args.out_dir).resolve()
    matlab_exe = Path(args.matlab)

    if not bsds_root.exists():
        raise FileNotFoundError(f"BSDS root not found: {bsds_root}")
    if not pred_dir.exists():
        raise FileNotFoundError(f"Prediction dir not found: {pred_dir}")
    out_dir.mkdir(parents=True, exist_ok=True)

    # Generate eval script (self-contained, locks down MATLAB path)
    matlab_script = repo_root / "tools" / "eval_bsds500_official.m"
    _write_matlab_eval_script(
        matlab_script, repo_root, bsds_root, pred_dir, out_dir, eval_type=args.eval_type
    )

    # Extra env: MATLABPATH (Windows separator ';')
    bench_path = str((repo_root / "tools" / "BSDSbench").resolve())
    pdollar_path = str((repo_root / "tools" / "pdollar_toolbox").resolve())
    extra_env = {"MATLABPATH": bench_path + ";" + pdollar_path}

    _run_matlab(matlab_exe, matlab_script, cwd=repo_root, extra_env=extra_env)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
